kind: pipeline
name: default

steps:
  - name: test
    image: gradle:jdk16
    commands:
      - gradle assemble
      - gradle check

  - name: publish to Dockerhub image
    image: plugins/docker
    settings:
      auto_tag: true
      repo: thomaslacaze/lab1
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
      - push
      - tag
      branch:
      - master
      - main

  - name: publish readme to Dockerhub
    image: thomaslacaze/dockerhub-description:2.4.1
    pull: always
    settings:
      repository: thomaslacaze/lab1
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      readme: /drone/src/README.md
    when:
      branch:
      - master
      - main